### ISSUE TITLE
Probable inconsistency in ES sample for delete case

### ISSUE THREAD

**Issue by saumehta9** [AWS-South-Wales-User-Group/qldb-simple-demo#17]
I think there could be a problem with the delete case in the ElasticSearch sample. 

Let's say at QLDB side -> `UPDATE[id=2], DELETE[id=2]`
And since Stream records can be duplicate and out of order, let's say the lambda (that persists to ES) gets -  `UPDATE[id=2], DELETE[id=2], UPDATE[id=2]`, the eventual picture on ES side will be incorrect.

* Note: `UPDATE[id=2]` means `PUT id=2` in terms of ES

I think we need to tombstone record in ES instead of deleting or maybe use ES feature [gc_deletes](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html#dynamic-index-settings) .

**Comment by mlewis7127** [comment]
Thank you for this comment. We essentially create a tombstone record in DynamoDB to cater for the delete case. For ES in this current implementation, the default `gc_deletes` default setting of 60 seconds was enough to cater for out of order or duplicate records, alongside the external versioning. It's definitely something to consider, as we never had significant volumes of records in a ledger when setting up a stream. I'm now trying to decide how best to reflect this

**Comment by mlewis7127** [comment]
I have just migrated ElasticSearch to OpenSearch, and in the process added a tombstone record to support the problem you noted above
